task_manager/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from rest_framework import routers
from tasks.apiviews import TaskHistoryViewSet, TaskViewSet
from tasks.auth import UserCreateView, UserLoginView
from tasks.views import (GenericCompletedTaskView, GenericPendingTaskView,
                         GenericTaskCompleteView, GenericTaskCreateView,
                         GenericTaskDeleteView, GenericTaskDetailView,
                         GenericTaskUpdateView, GenericTaskView, GenericReportView)

router = routers.SimpleRouter()
router.register(r'api_tasks', TaskViewSet)
router.register(r"taskHistory", TaskHistoryViewSet)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("tasks/", GenericTaskView.as_view()),
    path("pending-tasks/", GenericPendingTaskView.as_view()),
    path("update-task/<pk>/", GenericTaskUpdateView.as_view()),
    path("detail-task/<pk>/", GenericTaskDetailView.as_view()),
    path("create-task/", GenericTaskCreateView.as_view()),
    path("delete-task/<pk>", GenericTaskDeleteView.as_view()),
    path("user/signup", UserCreateView.as_view()),
    path("user/login", UserLoginView.as_view()),
    path("user/logout", LogoutView.as_view()),
    path("complete_task/<pk>/", GenericTaskCompleteView.as_view()),
    path("completed_tasks/", GenericCompletedTaskView.as_view()),
     path("report-settings/<pk>", GenericReportView.as_view()),
    path("", include(router.urls))
    # path("all_tasks/", all_tasks_view)
]

tasks/models.py
from django.db import models
from datetime import datetime, timezone
from django.contrib.auth.models import User

from django.dispatch import receiver
from django.db.models.signals import post_save

STATUS_CHOICES = (
    ("PENDING", "PENDING"),
    ("IN_PROGRESS", "IN_PROGRESS"),
    ("COMPLETED", "COMPLETED"),
    ("CANCELLED", "CANCELLED"),
)

class Task(models.Model):
    _old_status = None

    title = models.CharField(max_length=100)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)
    priority = models.IntegerField(null=True, blank=True)
    status = models.CharField(
        max_length=100, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0]
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __init__(self,  *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._old_status = self.status


class TaskHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    old_status = models.CharField(max_length=100, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0])
    new_status = models.CharField(max_length=100, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0])
    time_of_change = models.DateTimeField(auto_now=True)

class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null = True, blank = True)
    timing = models.IntegerField(default = 0)
    last_report = models.DateTimeField(null=True, default=datetime.now(timezone.utc).replace(hour=0))

@receiver(post_save, sender=User)
def addReport(instance, **kwargs):
    user = User.objects.get(pk=instance.id)
    report = Report.objects.filter(user=user)
    if report.count() <= 0:
        Report.objects.create(
            user=user,
            timing=0
        )

tasks/forms.py
from django.forms import ModelForm
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.models import Task
from tasks.models import Report

class TaskCreateForm(LoginRequiredMixin, ModelForm):
    def clean_title(self):
        title = self.cleaned_data["title"]
        return title

    class Meta:
        model = Task
        fields = ["title", "description", "priority", "completed"]

class ReportForm(ModelForm):

    class Meta:
        model = Report
        fields = ["timing"]

tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from tasks.forms import TaskCreateForm, ReportForm
from tasks.models import Task, Report
from django.db import transaction


class GenericTaskView(LoginRequiredMixin, ListView):
    queryset = Task.objects.filter(deleted=False)
    template_name = "tasks.html"
    context_object_name = "tasks"
    paginate_by = 3

    def get_queryset(self):
        search_term = self.request.GET.get("search")
        current_tasks = Task.objects.filter(
            deleted=False, user=self.request.user
        ).order_by("completed", "priority")
        if search_term:
            current_tasks = current_tasks.filter(title__icontains=search_term)
        return current_tasks
    
    def get_context_data(self, **kwargs):          
        context = super().get_context_data(**kwargs)                     
        completed = Task.objects.filter(
            deleted=False, user=self.request.user, completed=True
        ).count
        context["completed"] = completed
        return context

class GenericCompletedTaskView(LoginRequiredMixin, ListView):
    queryset = Task.objects.filter(deleted=False)
    template_name = "completed_tasks.html"
    context_object_name = "tasks"
    paginate_by = 3

    def get_queryset(self):
        current_tasks = Task.objects.filter(
            deleted=False, completed=True, user=self.request.user
        )
        return current_tasks

class GenericTaskCreateView(LoginRequiredMixin, CreateView):
    form_class = TaskCreateForm
    template_name = "task_create.html"
    success_url = "/tasks"

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        helper(self.request.user, int(form.cleaned_data.get("priority")), form)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class GenericPendingTaskView(LoginRequiredMixin, ListView):
    queryset = Task.objects.filter(deleted=False)
    template_name = "pending_tasks.html"
    context_object_name = "tasks"
    paginate_by = 3

    def get_queryset(self):
        search_term = self.request.GET.get("search")
        current_tasks = Task.objects.filter(
            deleted=False, completed=False, user=self.request.user
        ).order_by("priority")
        if search_term:
            current_tasks = current_tasks.filter(title__icontains=search_term)
        return current_tasks

class AuthorisedTaskManager(LoginRequiredMixin):
    def get_queryset(self):
        return Task.objects.filter(deleted=False, user=self.request.user)


class GenericTaskDetailView(AuthorisedTaskManager, DetailView):
    model = Task
    template_name = "task_detail.html"


class GenericTaskUpdateView(AuthorisedTaskManager, UpdateView):
    model = Task
    form_class = TaskCreateForm
    template_name = "task_update.html"
    success_url = "/tasks"

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        helper(self.request.user, int(form.cleaned_data.get("priority")), form)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class GenericTaskDeleteView(AuthorisedTaskManager, DeleteView):
    model = Task
    template_name = "task_delete.html"
    success_url = "/tasks"


class GenericTaskCompleteView(AuthorisedTaskManager, UpdateView):
    model = Task
    fields = ["completed"]
    template_name = "task_complete.html"
    success_url = "/tasks"

class GenericReportView(UpdateView):
    form_class = ReportForm
    template_name = "report.html"
    success_url = "/tasks"

    def get_queryset(self):
        return Report.objects.filter(user=self.request.user)

def helper(user, priority, form):
    if Task.objects.filter(
        deleted=False, user=user, priority=priority, completed=False
    ).exists():
        old_tasks = (
            Task.objects.filter(
                deleted=False,
                user=user,
                priority__gte=priority,
                completed=False,
            )
            .exclude(pk=form.instance.id)
            .order_by("priority")
            .select_for_update()
        )

        changes = []
        flag = priority
        for task in old_tasks:
            if flag != task.priority:
                break
            task.priority = task.priority + 1
            flag = flag + 1
            changes.append(task)

        with transaction.atomic():
            if changes:
                Task.objects.bulk_update(changes, ["priority"], batch_size=100)

        return

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Task Manager</title>
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

templates/completed_tasks.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="flex justify-evenly">
  <div class="flex flex-col space-y-6 justify-center w-1/3.8">
    <div class="flex justify-between items-center mt-16">
      <p class="text-4xl font-bold">Hello {{request.user | capfirst}}</p>
      <a href="/user/logout" class="no-underline text-[#EF4444]">Logout</a>
    </div>

    <span class="text-xs text-[#64748B]">
      {{ tasks|length }} tasks completed
    </span>

    <div class="flex justify-between items-center mt-16">
      <a href="/tasks/" class="py-2 px-8 rounded-3xl">All</a>
      <a href="/pending-tasks/" class="py-2 px-8 rounded-3xl">Pending</a>
      <a
        href="/completed_tasks"
        class="py-2 px-8 rounded-3xl bg-[#FFE4E6] text-[#EF4444]"
        >Completed</a
      >
    </div>

    <div class="flex flex-col space-y-5">
      {% for item in tasks %}
      <div
        class="flex bg-[#F1F5F9] rounded-2xl px-6 py-4 justify-between items-center"
      >
        <div class="flex flex-col justify-center">
          <div class="font-medium line-through text-[#F43F5E]">
            {{ item.title }}
          </div>
          <div class="text-[#94A3B8] text-xs">{{item.created_date.date }}</div>
        </div>

        <div class="flex">
          <a href="/delete-task/{{ item.id }}">
            <div
              class="flex bg-[#F43F5E] rounded-lg w-max px-2 py-2 w-9 justify-center"
            >
              {% load static %}
              <img src="{% static 'tasks/delete.png' %}" />
            </div>
          </a>
          <a href="/update-task/{{ item.id }}">
            <div
              class="flex bg-[#2DD4BF] rounded-lg w-max px-2 py-2 w-9 justify-center ml-2"
            >
              {% load static %}
              <img src="{% static 'tasks/pencil.png' %}" />
            </div>
          </a>
        </div>
      </div>

      {% endfor %}
      <div class="flex justify-around">
        {% for page in paginator.page_range %}
          <a href="?page={{ page }}">{{ page }}</a>
        {% endfor %}
      </div>

    </div>
  </div>
</div>
{% endblock %}

templates/pending_tasks.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="flex justify-evenly">

  <div class="flex flex-col space-y-6 justify-center w-1/3.8">

    <div class="flex justify-between items-center mt-16">
      <p class="text-4xl font-bold">Hello {{request.user | capfirst}}</p>
      <a href="/user/logout" class="no-underline text-[#EF4444]">Logout</a>
    </div>

    <span class="text-xs text-[#64748B]">
      {{ tasks.count }} tasks pending
    </span>

    <div class="flex justify-between items-center mt-16">
      <a href="/tasks" class="py-2 px-8 rounded-3xl">All</a>
      <a
        href="/pending-tasks/"
        class="py-2 px-8 rounded-3xl bg-[#FFE4E6] text-[#EF4444]"
        >Pending</a
      >
      <a href="/completed_tasks" class="py-2 px-8 rounded-3xl">Completed</a>
    </div>

    <div class="flex flex-col space-y-5">
      {% for item in tasks %}
      <div
        class="flex bg-[#F1F5F9] rounded-2xl px-6 py-4 justify-between items-center"
      >
        <div class="flex flex-col justify-center">
          <div class="font-medium">{{ item.title }}</div>
          <div class="text-[#64748B] text-xs">{{item.created_date.date | date:"D d M" }}</div>
        </div>

        <div class="flex">
          <a href="/delete-task/{{ item.id }}">
            <div
              class="flex bg-[#F43F5E] rounded-lg w-max px-2 py-2 w-9 justify-center"
            >
              {% load static %}
              <img src="{% static 'tasks/delete.png' %}" />
            </div>
          </a>

          <a href="/update-task/{{ item.id }}">
            <div
              class="flex bg-[#2DD4BF] rounded-lg w-max px-2 py-2 w-9 justify-center ml-2"
            >
              {% load static %}
              <img src="{% static 'tasks/pencil.png' %}" />
            </div>
          </a>
        </div>
      </div>

      {% endfor %}
      <div class="flex justify-around">
        {% for page in paginator.page_range %}
          <a href="?page={{ page }}">{{ page }}</a>
        {% endfor %}
      </div>

      <a href="/create-task/">
        <button
          class="rounded-md bg-blue-500 py-2 px-4 text-white w-full bg-[#EF4444] mb-10"
        >
          Add
        </button>
      </a>
    </div>
  </div>
</div>
{% endblock %}

templates/report.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="flex justify-evenly">
  <div class="flex flex-col space-y-6 justify-center w-1/3.8">
    <h1 class="text-5xl font-bold pb-8">Report Settings</h1>
    <form method="post">
      <div>
        <label for="id_time"
          >When would you like to get your daily report ?</label
        >
        {% comment %}
        <input
          type="time"
          name="timing"
          required
          id="id_time"
          class="p-3 bg-gray-200 rounded-xl block w-full my-2 text-base text-black"
        />
        {% endcomment %}
        <input
          type="number"
          name="timing"
          min="0"
          max="23"
          id="id_time"
          class="appearance-none rounded-md w-full py-2 px-3 leading-tight bg-[#F1F5F9]"
        />
      </div>
      {% csrf_token %}
      <input
        type="submit"
        value="Add"
        class="rounded-md bg-blue-500 py-2 px-4 text-white w-full bg-[#EF4444] my-10"
      />
    </form>
  </div>
</div>
{% endblock %}

templates/task_complete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Update" />
</form>
{% endblock %}

templates/task_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="flex justify-evenly">
  <div class="flex flex-col h-screen space-y-10 justify-center w-2/6">
    <h1 class="text-5xl font-bold pb-8">Create Todo</h1>
    <form method="post">
      <div class="flex flex-col space-y-4">
        <div>
          <label for="id_title">Title</label>
          <input
            type="text"
            name="title"
            maxlength="100"
            required
            id="id_title"
            class="appearance-none rounded-md w-full py-2 px-3 leading-tight bg-[#F1F5F9]"
          />
        </div>

        <div>
          <label for="id_description">Description:</label>
          <textarea
            name="description"
            cols="40"
            rows="10"
            required
            id="id_description"
            class="appearance-none rounded-md w-full py-2 px-3 leading-tight bg-[#F1F5F9]"
          ></textarea>
        </div>

        <div>
          <label for="id_priority">Priority</label>
          <input
            type="number"
            name="priority"
            id="id_priority"
            class="appearance-none rounded-md w-full py-2 px-3 leading-tight bg-[#F1F5F9]"
          />
        </div>

        <div class="flex">
          <input
            type="checkbox"
            name="completed"
            id="id_completed"
            class="appearance-none checked:bg-blue-500 rounded-md py-3 px-3 mr-4 leading-tight bg-[#F1F5F9]"
          />
          <label for="id_completed">Completed</label>
        </div>
        {% csrf_token %}
        <input
          type="submit"
          value="Add"
          class="rounded-md bg-blue-500 py-2 px-4 text-white w-full bg-[#EF4444] my-10"
        />
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/task_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="flex justify-evenly">
  <div class="flex flex-col h-screen justify-evenly w-1/3.8 ">
    <form method="post">
      <div class="flex flex-col space-y-4 bg-[#F1F5F9] rounded-2xl px-6 py-6">
      {%csrf_token%}
      <p>Are you sure you want to delete "{{ object }}" ?</p>
      <input
        type="submit"
        value="Confirm"
        class="rounded-md bg-blue-500 py-2 px-4 text-white w-full bg-[#EF4444] mb-10"
      />
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/task_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>Titlle</h2>
{{object.title}}
<h2>Desctiption</h2>
{{object.description}}
<h2>Created At</h2>
{{object.created_date}}
{%endblock%}

templates/task_update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="flex justify-evenly">
  <div class="flex flex-col h-screen space-y-10 justify-center w-2/6">
    <h1 class="text-5xl font-bold pb-8">Update Todo</h1>
    <form method="post">
      {% csrf_token %}
      <div class="flex flex-col space-y-4">
        <div>
          <label for="{{ form.title.id_for_label }}">Title</label>
          {{form.title}}
        </div>

        <div>
          <label for="{{ form.description.id_for_label }}">Description</label>
          {{form.description}}
        </div>

        <div>
          <label for="{{ form.priority.id_for_label }}">Priority</label>
          {{form.priority}}
        </div>

        <div class="flex">
          {{form.completed}}
          <label for="{{ form.completed.id_for_label }}">Completed</label>
        </div>

        <input
          type="submit"
          value="Update Task"
          class="rounded-md bg-blue-500 py-2 px-4 text-white w-full bg-[#EF4444] my-10"
        />
      </div>
    </form>
  </div>
</div>
{%endblock%}

templates/tasks.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="flex justify-evenly">

  <div class="flex flex-col space-y-6 justify-center w-1/3.8">

    <div class="flex justify-between items-center mt-16">
      <p class="text-4xl font-bold">Hello {{request.user | capfirst}}</p>
      <a href="/user/logout" class="no-underline text-[#EF4444]">Logout</a>
    </div>

    <span class="text-xs text-[#64748B]">
      {{completed}} of {{tasks.count}} tasks completed
    </span>

    <div class="flex justify-between items-center mt-16">
      <a
        href="/tasks/"
        class="py-2 px-8 rounded-3xl bg-[#FFE4E6] text-[#EF4444]"
        >All</a
      >
      <a href="/pending-tasks/" class="py-2 px-8 rounded-3xl">Pending</a>
      <a href="/completed_tasks" class="py-2 px-8 rounded-3xl">Completed</a>
    </div>

    <div class="flex flex-col space-y-5">
      {% for item in tasks %}
      <div
        class="flex bg-[#F1F5F9] rounded-2xl px-6 py-4 justify-between items-center"
      >
        {% if item.completed %}

        <div class="flex flex-col justify-center">

          <div class="font-medium line-through text-[#F43F5E]">
            {{ item.title }}
          </div>

          <div class="text-[#94A3B8] text-xs">
            {{item.created_date | date:"D d M" }}
          </div>

        </div>

        {% else %}

        <div class="flex flex-col justify-center">

          <div class="font-medium">{{ item.title }}</div>

          <div class="text-[#64748B] text-xs">{{item.created_date | date:"D d M"}}</div>
        </div>

        {% endif %}

        <div class="flex">

          <a href="/delete-task/{{ item.id }}">
            <div
              class="flex bg-[#F43F5E] rounded-lg w-max px-2 py-2 w-9 justify-center"
            >
              {% load static %}
              <img src="{% static 'tasks/delete.png' %}" />
            </div>
          </a>

          <a href="/update-task/{{ item.id }}">
            <div
              class="flex bg-[#2DD4BF] rounded-lg w-max px-2 py-2 w-9 justify-center ml-2"
            >
              {% load static %}
              <img src="{% static 'tasks/pencil.png' %}" />
            </div>
          </a>

        </div>
      </div>

      {% endfor %}
      <div class="flex justify-around">
        {% for page in paginator.page_range %}
          <a href="?page={{ page }}">{{ page }}</a>
        {% endfor %}
      </div>

      <a href="/create-task/">
        <button
          class="rounded-md bg-blue-500 py-2 px-4 text-white w-full bg-[#EF4444] mb-10"
        >
          Add
        </button>
      </a>

    </div>
  </div>
</div>
{% endblock %}

templates/user_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="flex justify-evenly">

  <div class="flex flex-col h-screen space-y-10 justify-center w-1/3.8">

    <h1 class="text-5xl font-bold pb-8">Todo Manager</h1>
    <h2 class="text-3xl mb-4">Signup</h2>

    <form action="" method="post">
      <div class="flex flex-col space-y-4">

        <div>
          <label for="id_username">Username</label>
          <input
            type="text"
            name="username"
            maxlength="150"
            autocapitalize="none"
            autocomplete="username"
            autofocus
            required
            id="id_username"
            class="appearance-none rounded-md w-full py-2 px-3 leading-tight bg-[#F1F5F9] my-2"
          />
          <p class="text-xs text-[#64748B]">
            150 characters or fewer. Letters, digits and @/./+/-/_ only.
          </p>
        </div>

        <div>
          <label for="id_password1">Password</label>
          <input
            type="password"
            name="password1"
            autocomplete="new-password"
            required
            id="id_password1"
            class="appearance-none rounded-md w-full py-2 px-3 leading-tight bg-[#F1F5F9] my-2"
          />

          <span class="text-xs text-[#64748B] w-full">
            <ul class="list-disc ml-8">
              <li>
                Your password can't be too similar to your other personal
                information.
              </li>
              <li>Your password must contain at least 8 characters.</li>
              <li>Your password can't be a commonly used password.</li>
              <li>Your password can't be entirely numeric.</li>
            </ul>
          </span>
        </div>

        <div>
          <label for="id_password2">Confirm Password</label>
          <input
            type="password"
            name="password2"
            autocomplete="new-password"
            required
            id="id_password2"
            class="appearance-none rounded-md w-full py-2 px-3 leading-tight bg-[#F1F5F9] my-2"
          />
          {% csrf_token %}
          <input
            type="submit"
            value="Sign Up"
            class="rounded-md bg-blue-500 py-2 px-4 text-white w-full bg-[#EF4444] my-10"
          />
        </div>
      </div>
    </form>
  </div>
</div>
{%endblock%}

templates/user_login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="flex justify-evenly">
  <div class="flex flex-col h-screen space-y-10 justify-center w-1/3.8">
    <h1 class="text-5xl font-bold pb-8">Todo Manager</h1>
    <h2 class="text-3xl mb-4">Login</h2>

    <form action="" method="post">
      <div class="flex flex-col space-y-4">
        <div>
          <label for="id_username">Username</label>
          <input
            type="text"
            name="username"
            autofocus=""
            autocapitalize="none"
            autocomplete="username"
            maxlength="150"
            required=""
            id="id_username"
            class="appearance-none rounded-md w-full py-2 px-3 leading-tight bg-[#F1F5F9]"
          />
        </div>

        <div>
          <label for="id_password">Password</label>
          <br />
          <input
            type="password"
            name="password"
            autocomplete="current-password"
            required=""
            id="id_password"
            class="appearance-none rounded-md w-full py-2 px-3 text-gray-700 leading-tight bg-[#F1F5F9]"
          />
        </div>
        {% csrf_token %}
        <div>
          <input
            type="submit"
            value="Login"
            class="rounded-md bg-blue-500 py-2 px-4 text-white w-full bg-[#EF4444] my-10"
          />
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}